-- TẠO DATABASE
CREATE DATABASE TaskManagementDB;
GO

-- CHỌN DATABASE
USE TaskManagementDB;
GO


-- USERS
CREATE TABLE Users (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    name NVARCHAR(150) NOT NULL,
    email NVARCHAR(150) NOT NULL,
    password NVARCHAR(255) NULL,
    role NVARCHAR(20) NOT NULL,
    avatar NVARCHAR(500) NULL
);
GO


-- PROJECTS
CREATE TABLE Projects (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    name NVARCHAR(200) NOT NULL,
    description NVARCHAR(500) NULL,
    managerId UNIQUEIDENTIFIER NOT NULL,
    createdAt DATETIME2 NULL,

    FOREIGN KEY (managerId) REFERENCES Users(id)
);
GO


-- PROJECT MEMBERS
CREATE TABLE ProjectMembers (
    projectId UNIQUEIDENTIFIER NOT NULL,
    userId UNIQUEIDENTIFIER NOT NULL,

    PRIMARY KEY (projectId, userId),

    FOREIGN KEY (projectId) REFERENCES Projects(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
GO


-- TASKS
CREATE TABLE Tasks (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    projectId UNIQUEIDENTIFIER NOT NULL,
    title NVARCHAR(200) NOT NULL,
    description NVARCHAR(500) NULL,
    assigneeId UNIQUEIDENTIFIER NULL,
    creatorId UNIQUEIDENTIFIER NOT NULL,
    status NVARCHAR(20) NOT NULL,
    startDate DATETIME2 NULL,
    deadline DATETIME2 NULL,
    createdAt DATETIME2 NULL,
    deadlineNotified BIT NULL,

    FOREIGN KEY (projectId) REFERENCES Projects(id) ON DELETE CASCADE,
    FOREIGN KEY (assigneeId) REFERENCES Users(id),
    FOREIGN KEY (creatorId) REFERENCES Users(id)
);
GO


-- SUBTASKS
CREATE TABLE Subtasks (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    taskId UNIQUEIDENTIFIER NOT NULL,
    title NVARCHAR(200) NOT NULL,
    status NVARCHAR(20) NOT NULL,
    startDate DATETIME2 NULL,
    deadline DATETIME2 NULL,

    FOREIGN KEY (taskId) REFERENCES Tasks(id) ON DELETE CASCADE
);
GO


-- COMMENTS
CREATE TABLE Comments (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    taskId UNIQUEIDENTIFIER NOT NULL,
    userId UNIQUEIDENTIFIER NOT NULL,
    content NVARCHAR(MAX) NOT NULL,
    createdAt DATETIME2 NULL,

    FOREIGN KEY (taskId) REFERENCES Tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES Users(id)
);
GO


-- NOTIFICATIONS
CREATE TABLE Notifications (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    userId UNIQUEIDENTIFIER NOT NULL,
    message NVARCHAR(500) NOT NULL,
    isRead BIT NULL,
    createdAt DATETIME2 NULL,

    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
GO